## Упражнения по библиотеке Numpy

In [1]:
import numpy as np


**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [2]:
arr = np.array(np.random.randint(-5, 10, 50))
print('Arr:\n', arr)

arr[(arr > 3) & (arr < 8)] *= -1
#arr = np.where((arr > 3) & (arr < 8), -arr, arr)
print('New arr:\n', arr)

Arr:
 [-3 -5  6  1 -4 -5 -2 -5 -5  1  3  3  9  6 -1 -1  5  1 -4  3  0  8 -1  8
  7  5 -2 -4 -4  4  8  9  1  4 -2  7  7  0 -4 -2  7  0 -4  2  4  9 -3 -2
 -4  0]
New arr:
 [-3 -5 -6  1 -4 -5 -2 -5 -5  1  3  3  9 -6 -1 -1 -5  1 -4  3  0  8 -1  8
 -7 -5 -2 -4 -4 -4  8  9  1 -4 -2 -7 -7  0 -4 -2 -7  0 -4  2 -4  9 -3 -2
 -4  0]


**2.** Заменить максимальный элемент случайного массива на 0

In [3]:
arr = np.array(np.random.randint(-5, 10, 50))
print('Arr:\n', arr)
print('Max:', np.max(arr), '\tIndex:', np.argmax(arr))

arr[np.argmax(arr)] = 0
print('New arr:\n', arr)

Arr:
 [ 7 -3  6 -2  7  6  4  5  9 -2  6  2  1  6 -1  1  7 -4  3 -4  7 -3  4  4
 -1  6  8  9  6 -2 -4 -4 -4 -4 -1 -1  2  4  2  8 -4  7  8  5  5  9  1  6
  6  6]
Max: 9 	Index: 8
New arr:
 [ 7 -3  6 -2  7  6  4  5  0 -2  6  2  1  6 -1  1  7 -4  3 -4  7 -3  4  4
 -1  6  8  9  6 -2 -4 -4 -4 -4 -1 -1  2  4  2  8 -4  7  8  5  5  9  1  6
  6  6]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [4]:
mat = np.array(np.random.randint(-5, 10, 6)).reshape(3, 2)
print('Mat:\n',mat)

arrays = [np.asarray(row) for row in mat]
shape = map(len, arrays)

grid = np.indices(shape)
grid = grid.reshape(len(arrays), -1).T

for n, arr in enumerate(arrays):
    grid[:, n] = arrays[n][grid[:, n]]

print('Res:\n', grid)

Mat:
 [[ 1 -5]
 [ 6 -4]
 [ 5  1]]
Res:
 [[ 1  6  5]
 [ 1  6  1]
 [ 1 -4  5]
 [ 1 -4  1]
 [-5  6  5]
 [-5  6  1]
 [-5 -4  5]
 [-5 -4  1]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [5]:
A = np.array(np.random.randint(0, 5, 24)).reshape(8, 3)
B = np.array(np.random.randint(0, 5, 4)).reshape(2, 2)
print('A:\n', A)
print('B:\n', B)

# Создаем четырехмерную матрицу С, чтобы каждый элемент был двумерным массивом(размера матрицы В)
# Затем проводим точное сравнение, чтобы хоть 1 элемент из строки В, был равен элементу в виде двумерной матрицы.
# Затем суммируем все значения на осях, кроме 0 - это строки А, и сравниваем с числом столбцов В, если >=,
# то строка подходит, иначе будет ноль, которые мы отбросим. В результате получим индексы подходящих строк.
C = A[:, :, np.newaxis, np.newaxis] == B
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print('rows', rows)

A:
 [[3 4 0]
 [1 2 2]
 [2 3 4]
 [2 4 0]
 [3 2 2]
 [4 1 0]
 [3 3 3]
 [4 0 3]]
B:
 [[2 1]
 [1 4]]
rows [1 2 3 4 5]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [6]:
mat = np.random.randint(0, 4, (10, 3))
print('mat:\n', mat)

res = []
for row in mat:
    if len(np.unique(row)) != 1:
        res.append(row)
print('Res:\n', np.array(res))

mat:
 [[2 2 2]
 [0 3 0]
 [1 3 3]
 [2 0 2]
 [3 3 1]
 [1 1 0]
 [0 0 3]
 [1 1 3]
 [2 3 0]
 [0 3 3]]
Res:
 [[0 3 0]
 [1 3 3]
 [2 0 2]
 [3 3 1]
 [1 1 0]
 [0 0 3]
 [1 1 3]
 [2 3 0]
 [0 3 3]]


In [7]:
# Смотрим, чтобы все элементы строки матрицы в 1 и 2 столбце равнялись элементам в 0 и в 1,
# если это так, то строка удаляется. Инвертируем, чтобы вывести не эти строки.
mask = np.logical_and.reduce(mat[:,1:] == mat[:,:-1], axis=1)
res = mat[~mask]
print(res)

[[0 3 0]
 [1 3 3]
 [2 0 2]
 [3 3 1]
 [1 1 0]
 [0 0 3]
 [1 1 3]
 [2 3 0]
 [0 3 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
mat = np.array(np.random.randint(0, 3, (10, 3)))
print('Mat:\n', mat)

u, ind = np.unique(mat, axis=0, return_index=True)
res = u[ind.argsort()]
print('Res:\n', res)

Mat:
 [[2 2 2]
 [1 0 2]
 [0 2 0]
 [2 0 0]
 [1 2 0]
 [1 1 1]
 [1 1 0]
 [2 2 1]
 [1 1 2]
 [0 0 2]]
Res:
 [[2 2 2]
 [1 0 2]
 [0 2 0]
 [2 0 0]
 [1 2 0]
 [1 1 1]
 [1 1 0]
 [2 2 1]
 [1 1 2]
 [0 0 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
# no numpy example
import random
from functools import reduce

rows = 4
cols = 5
mat = [[random.randint(0, 5) for i in range(cols)] for j in range(rows)]
print('Mat:', mat)
res = reduce(lambda a, b: a*b,\
             [mat[i][i] for i in range(min(rows, cols)) if mat[i][i] != 0], 1)
print('Res:', res)

Mat: [[0, 0, 3, 4, 1], [1, 3, 2, 3, 3], [3, 1, 2, 3, 2], [1, 1, 3, 5, 0]]
Res: 30


In [10]:
# numpy
np.prod(np.diag(mat)[np.diag(mat) != 0])

30

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [11]:
# no numpy
x = [random.randint(-5, 4) for i in range(5)]
y = [random.randint(-5, 4) for i in range(5)]
print('x:', x)
print('y:', y)
print(sorted(set(x)) == sorted(set(y))) # Множества не стоит сравнивать на точное равенство, потому что порядок элементов не важен в них

x: [-5, -1, -4, -5, -4]
y: [4, -4, -5, 2, -4]
False


In [12]:
# numpy
len(np.setxor1d(x, y)) == 0

False

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [13]:
# no numpy
x = [random.randint(0, 7) for i in range(20)]
print(x)
res = max([x[i] for i in range(1, len(x)) if x[i-1] == 0])
print(res)

[2, 0, 0, 2, 1, 1, 7, 1, 5, 6, 3, 3, 2, 0, 3, 5, 2, 1, 2, 0]
3


In [14]:
# numpy
x = np.array(x)
mask = x == 0
print(x[1:][mask[:-1]].max())

3


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [15]:
# no numpy
import random
x = [random.randint(-5, 5) for i in range(10)]
print('X:', sorted(x))
items = sorted(list(set(x)))
res = (items, [x.count(item) for item in items])
print('Res:', res)

X: [-4, -3, -3, -3, -1, 0, 1, 2, 3, 4]
Res: ([-4, -3, -1, 0, 1, 2, 3, 4], [1, 3, 1, 1, 1, 1, 1, 1])


In [16]:
# numpy
np.unique(x, return_counts=True)

(array([-4, -3, -1,  0,  1,  2,  3,  4]), array([1, 3, 1, 1, 1, 1, 1, 1]))

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [99]:
# no numpy
import math
size = 3
X = [[random.randint(-5, 5) for i in range(size)] for j in range(size)]
print('X:', X)
Y = [[random.randint(-5, 5) for i in range(size)] for j in range(size)]
print('Y:', Y)
dist = [[math.dist(X[j], Y[i]) for i in range(size)]for j in range(size)]
print('\nDist:', dist)

X: [[-2, -1, 2], [-1, -5, 1], [-5, 2, 5]]
Y: [[-1, 2, 1], [-2, 4, 4], [0, 0, 5]]

Dist: [[3.3166247903554003, 5.385164807134505, 3.741657386773941], [7.0, 9.539392014169458, 6.48074069840786], [5.656854249492381, 3.741657386773941, 5.385164807134505]]


In [100]:
%%time
dist = [[math.dist(X[j], Y[i]) for i in range(size)] for j in range(size)] # 1

CPU times: user 21 µs, sys: 4 µs, total: 25 µs
Wall time: 29.1 µs


In [101]:
# numpy
X = np.matrix(X)
Y = np.matrix(Y)
dist = [[np.linalg.norm(X[j] - Y[i]) for i in range(size)] for j in range(size)]
print(dist)

[[3.3166247903554, 5.385164807134504, 3.7416573867739413], [7.0, 9.539392014169456, 6.48074069840786], [5.656854249492381, 3.7416573867739413, 5.385164807134504]]


In [102]:
%%time
dist = [[np.linalg.norm(X[j] - Y[i]) for i in range(size)] for j in range(size)] #2

CPU times: user 1.46 ms, sys: 264 µs, total: 1.73 ms
Wall time: 1.16 ms


In [103]:
import scipy.spatial

In [104]:
%%time
scipy.spatial.distance.cdist(X, Y)#3

CPU times: user 103 µs, sys: 18 µs, total: 121 µs
Wall time: 121 µs


array([[3.31662479, 5.38516481, 3.74165739],
       [7.        , 9.53939201, 6.4807407 ],
       [5.65685425, 3.74165739, 5.38516481]])

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [1]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [2]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [5]:
average_calories = calorie_stats.mean() - 60
average_calories

46.883116883116884

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [16]:
# your code
calorie_stats_sorted = sorted(calorie_stats)
calorie_stats_sorted

[50.0,
 50.0,
 50.0,
 70.0,
 70.0,
 80.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 90.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 100.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 110.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 120.0,
 130.0,
 130.0,
 140.0,
 140.0,
 140.0,
 150.0,
 150.0,
 160.0]

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [19]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [34]:
nth_percentile = np.percentile(calorie_stats, 4)
nth_percentile

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [40]:
more_calories = len(calorie_stats[calorie_stats > 60])/len(calorie_stats)*100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [41]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

 Стандартное отклонение отображает меру разброса данных, то есть, чем этот показатель выше, тем более разнообразны данные. Для бизнеса это значит, что на рынке представлены очень разнообразные хлопья, а наши хлопья занимают лидирующую позицию по меньшей калорийности. Ведь, если бы все конкуренты имели калорийность приблизительно как у нас, то этот показатель был бы намного меньше.

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

1. Если стандартное отклонение будет уменьшаться - значит у нас появляются конкуренты. С меньшей калорийностью хлопьев.
2. Если средняя разность калорий конкурентов и наша стремится к нулю, то мы теряем лидерство.
3. Чем меньше процентиль, тем лучше для нас.
4. Процент хлопьев, в которых содержится более 60 калорий на порцию говорит сам за себя, его нужно максимизировать.